#!/usr/bin/env python
"""Fail-closed tests for the V26C J15 fresh 35D post-mismatch refit.

Hermetic: the authorised leaf is never created. Every write path is exercised in a temporary root
through OUTPUT_ROOT_OVERRIDE. No rollout, no fit, no environment, and torch is never imported -
by the runner OR by this suite.

NOT BORN SPENT: the preflight-GO and leaf-absence assertions are CONDITIONAL on the leaf, so this
suite still runs as evidence after J15 commits.
"""
from __future__ import annotations
import ast, builtins, difflib, pathlib, hashlib, inspect, io, json, os, re, shutil, sys, tempfile, tokenize
from pathlib import Path
import numpy as np

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
# NO BYTECODE, SET BEFORE THE IMPORT BELOW. Importing the runner would otherwise write or refresh
# a .pyc under the validation root - before the guard is installed and before the opening snapshot
# is taken, so the write would be invisible to both. Setting this here is what makes the "not one
# byte" claim SELF-CONTAINED instead of dependent on PYTHONDONTWRITEBYTECODE being exported by
# whoever launches the suite.
sys.dont_write_bytecode = True
import v26c_j15_fresh_refit as J15  # noqa: E402

TEST_SRC = HERE.joinpath(Path(__file__).name).read_text()
# the pristine write primitives, captured at import time, before any guard exists
PRISTINE = {"open": builtins.open, "io_open": io.open, "path_open": Path.open,
                "os_open": os.open}

CHECKS = 0


def check(c, w):
    global CHECKS
    assert c, w
    CHECKS += 1


def expect(fn, exc, w):
    global CHECKS
    try:
        fn()
    except exc as e:
        CHECKS += 1
        return e
    raise AssertionError(f"expected {exc.__name__}: {w}")


def snapshot(root: Path) -> dict[str, str]:
    """EVERY regular file under root, hashed. NO EXCLUSION - __pycache__ is inside the guarded
    set, because generated bytecode is still a byte written under the validation root."""
    out: dict[str, str] = {}
    for p in sorted(root.rglob("*")):
        if p.is_file():
            out[str(p.relative_to(root))] = hashlib.sha256(p.read_bytes()).hexdigest()
    return out


# ================================================================ hermeticity ====================
# NOT ONE BYTE may be written, unlinked, renamed or removed under the real validation root while
# this suite runs. A `finally` that restores an artefact is NOT good enough: an interrupted suite
# would leave a frozen artefact corrupted or a source leaf marked invalid. So every negative test
# operates on a TEMPORARY MIRROR, and this guard makes the rule enforceable rather than a promise.

MIRROR: Path
ATTEMPTS: list[str] = []
_ALLOWED_ROOTS: list[Path] = []


def _under_here(target) -> bool:
    try:
        p = Path(os.fspath(target))
    except TypeError:
        return False
    p = p if p.is_absolute() else Path.cwd() / p
    try:
        p.resolve().relative_to(HERE.resolve())
    except (ValueError, OSError):
        return False
    for allowed in _ALLOWED_ROOTS:
        try:
            p.resolve().relative_to(allowed.resolve())
            return False
        except (ValueError, OSError):
            continue
    return True


class HermeticGuard:
    """Fail-closed: any write primitive aimed under HERE raises instead of touching the file."""

    _PATH_METHODS = ("write_text", "write_bytes", "mkdir", "unlink", "rmdir", "touch", "rename",
                     "replace", "symlink_to", "hardlink_to", "chmod")
    _OS_FUNCS = ("rename", "replace", "remove", "unlink", "mkdir", "makedirs", "rmdir", "truncate")

    def __enter__(self):
        self._path = {n: getattr(Path, n, None) for n in self._PATH_METHODS}
        self._os = {n: getattr(os, n, None) for n in self._OS_FUNCS}
        self._misc = {"open": builtins.open, "io_open": io.open, "path_open": Path.open,
                      "os_open": os.open,
                      "rmtree": shutil.rmtree, "copyfile": shutil.copyfile,
                      "copy2": shutil.copy2, "move": shutil.move,
                      "savez": np.savez, "savez_compressed": np.savez_compressed}

        def block(label, real, path_arg=0, is_method=False):
            def f(*a, **k):
                # An fd-relative call (dir_fd=) carries a BARE NAME, not a path: resolving it
                # against cwd would flag shutil.rmtree's own internal unlinks as violations even
                # when the tree being removed is in the temp root. Such calls are therefore
                # DELEGATED UNCHECKED. Scope of that exemption, stated narrowly and no wider:
                # this suite makes no direct fd-relative call (asserted by AST in _body), and the
                # only code reaching this branch is shutil.rmtree's own descent, whose entry point
                # is itself guarded. This is NOT a claim that fd-relative writes are covered in
                # general - an fd-relative write from code outside this suite would pass through.
                if k.get("dir_fd") is not None:
                    return real(*a, **k)
                target = a[0] if is_method else (a[path_arg] if len(a) > path_arg else None)
                if target is not None and _under_here(target):
                    ATTEMPTS.append(f"{label}({target})")
                    raise AssertionError(f"HERMETICITY VIOLATION: {label} aimed at {target}, "
                                         f"which is under the real validation root")
                return real(*a, **k)
            return f

        for n, real in self._path.items():
            if real is not None:
                setattr(Path, n, block(f"Path.{n}", real, is_method=True))
        for n, real in self._os.items():
            if real is not None:
                setattr(os, n, block(f"os.{n}", real))
        shutil.rmtree = block("shutil.rmtree", self._misc["rmtree"])
        shutil.copyfile = block("shutil.copyfile", self._misc["copyfile"], path_arg=1)
        shutil.copy2 = block("shutil.copy2", self._misc["copy2"], path_arg=1)
        shutil.move = block("shutil.move", self._misc["move"], path_arg=1)
        np.savez = block("np.savez", self._misc["savez"])
        np.savez_compressed = block("np.savez_compressed", self._misc["savez_compressed"])

        real_open, real_os_open = self._misc["open"], self._misc["os_open"]

        def guarded_open(file, mode="r", *a, **k):
            if any(c in mode for c in "wax+") and _under_here(file):
                ATTEMPTS.append(f"open({file}, {mode!r})")
                raise AssertionError(f"HERMETICITY VIOLATION: open({file}, {mode!r}) under the "
                                     f"real validation root")
            return real_open(file, mode, *a, **k)

        def guarded_os_open(path, flags, *a, **k):
            writing = flags & (os.O_WRONLY | os.O_RDWR | os.O_CREAT | os.O_APPEND | os.O_TRUNC)
            if writing and _under_here(path):
                ATTEMPTS.append(f"os.open({path}, write)")
                raise AssertionError(f"HERMETICITY VIOLATION: os.open({path}) for writing under "
                                     f"the real validation root")
            return real_os_open(path, flags, *a, **k)

        # io.open and builtins.open are the SAME object on CPython, but pathlib captured the
        # original at class-definition time (3.10: _NormalAccessor.open = io.open), so patching
        # io.open does NOT reach Path.open. Both are patched, and each has its own probe.
        real_path_open = self._misc["path_open"]

        def guarded_path_open(self, mode="r", *a, **k):
            if any(c in mode for c in "wax+") and _under_here(self):
                ATTEMPTS.append(f"Path.open({self}, {mode!r})")
                raise AssertionError(f"HERMETICITY VIOLATION: Path.open({self}, {mode!r}) under "
                                     f"the real validation root")
            return real_path_open(self, mode, *a, **k)

        builtins.open, io.open, os.open = guarded_open, guarded_open, guarded_os_open
        Path.open = guarded_path_open
        return self

    def __exit__(self, *exc):
        for n, real in self._path.items():
            if real is not None:
                setattr(Path, n, real)
        for n, real in self._os.items():
            if real is not None:
                setattr(os, n, real)
        builtins.open, os.open = self._misc["open"], self._misc["os_open"]
        io.open, Path.open = self._misc["io_open"], self._misc["path_open"]
        shutil.rmtree, shutil.copyfile = self._misc["rmtree"], self._misc["copyfile"]
        shutil.copy2, shutil.move = self._misc["copy2"], self._misc["move"]
        np.savez, np.savez_compressed = self._misc["savez"], self._misc["savez_compressed"]
        return False


# the three trace files are 51 MB each and are never tampered, so they are symlinked rather than
# copied. Everything a negative test may touch is a REAL, INDEPENDENT copy.


# the J7 dataset and the J11 aggregate are large and are never tampered, so they are symlinked
# rather than copied. Everything a negative test may touch is a REAL, INDEPENDENT copy.
NEVER_TAMPERED = ("v26c_j7_markov_recovery_dataset.npz", "v26c_j11_aggregate_dataset.npz")


REAL_REPO = J15.REPO
REAL_HERE = J15.HERE


def _rel_repo(p) -> str:
    """A path relative to the REAL repository root - the same key space pinned_sources() uses."""
    return str(pathlib.PurePath(Path(p).resolve()).relative_to(REAL_REPO))


def build_mirror(tmp: Path) -> Path:
    """A complete, writable copy of every pinned source, laid out REPO-relative.

    use_mirror then points J15.REPO at this directory, so verify_sources() - which resolves
    REPO / rel_path - lands inside the mirror and never touches a real artefact.
    """
    mirror = tmp / "mirror"
    mirror.mkdir(exist_ok=True)
    extra = [J15.PREREG,
             REAL_HERE / "j11_runs/j11_multistart_fit_v26c_2026-08-27_r1/commit_verification.json",
             REAL_HERE / "j10r1_runs/j10r1_multistart_teacher_v26c_2026-08-27_r1/commit_verification.json",
             REAL_HERE / "j14_runs/j14_dagger_dataset_v26c_2026-08-27_r1/commit_verification.json",
             REAL_HERE / "j11_runs/j11_multistart_fit_v26c_2026-08-27_r1/v26c_j11_aggregate_dataset.npz",
             REAL_HERE / "j11_runs/j11_multistart_fit_v26c_2026-08-27_r1/rl_module/actor_feature_manifest.json"]
    wanted = list(J15.pinned_sources()) + [_rel_repo(q) for q in extra]
    for rel in sorted(set(wanted)):
        src = REAL_REPO / rel
        if not src.is_file():
            continue
        dst = mirror / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        if dst.exists() or dst.is_symlink():
            continue
        if src.name in NEVER_TAMPERED:
            dst.symlink_to(src)
        else:
            shutil.copyfile(src, dst)
    return mirror


class use_mirror:
    """Point every module path constant at the temporary mirror, then restore the REFERENCES.

    No file is written, moved or restored by this. Only Python attributes move. reset_mirror
    must be called OUTSIDE this context, when the real constants are back in place.
    """

    _CONSTS = ("HERE", "REPO", "PREREG", "J7_DATASET", "J7_RECEIPT", "J10R1_LEAF",
               "J10R1_RECEIPT", "J10R1_COMMIT_VERIFICATION", "J14_LEAF", "J14_DATASET",
               "J14_RECEIPT", "J14_COMMIT_VERIFICATION", "J11_LEAF", "J11_RECEIPT",
               "J11_COMMIT_VERIFICATION", "J11_STATE", "PARENT_MODULE_DIR", "CELL_DATASETS",
               "J11_MODULE", "J8_MODULE", "WARM_START_SOURCE", "ASYMMETRIC_RL_MODULE")

    def __init__(self, mirror: Path):
        self.mirror = mirror

    def __enter__(self):
        self.saved = {n: getattr(J15, n) for n in self._CONSTS}
        moved = lambda q: self.mirror / _rel_repo(q)
        for n in self._CONSTS:
            if n == "CELL_DATASETS":
                continue
            if n == "REPO":
                J15.REPO = self.mirror
                continue
            setattr(J15, n, moved(self.saved[n]))
        J15.CELL_DATASETS = {cid: (moved(path), pin)
                             for cid, (path, pin) in self.saved["CELL_DATASETS"].items()}
        return self.mirror

    def __exit__(self, *exc):
        for n, v in self.saved.items():
            setattr(J15, n, v)
        return False


def reset_mirror(mirror: Path) -> None:
    shutil.rmtree(mirror, ignore_errors=True)
    build_mirror(mirror.parent)


def main() -> int:
    global MIRROR
    tmproot = Path(tempfile.mkdtemp(prefix="v26c_j15_hermetic_"))
    _ALLOWED_ROOTS.append(tmproot)
    MIRROR = build_mirror(tmproot)
    try:
        with HermeticGuard():
            return _body(tmproot)
    finally:
        shutil.rmtree(tmproot, ignore_errors=True)
        _ALLOWED_ROOTS.clear()


def fake_fit() -> dict:
    """A tiny, deterministic test double. Never a real fit: no torch, no optimizer, no epochs."""
    data = J15.build_aggregate()
    parent = J15.load_parent_state()
    names = list(data["names"])
    final = {k: np.asarray(v, dtype=np.float32).copy() for k, v in parent.items()}
    final["pi.0.0.weight"][:, list(J15.CLOCK_COLUMNS)] = 0.0
    for c in range(*J15.CONTROLLER_SPAN):
        final["pi.0.0.weight"][:, c] = np.float32(0.01)
    for alias, direct in J15.ALIAS_PAIRS:
        final[alias] = final[direct].copy()
    act = data["actions"]
    before = np.zeros_like(act)
    after = act.copy()                      # a perfect "after": every RMSE strictly decreases
    return {"final": final, "parent": parent, "prereg": J15.verify_prereg(), "data": data,
            "split": J15.build_split(J15.TOTAL_ROWS),
            "history": [{"epoch": 1.0, "train_loss": 1.0, "validation_mse": 1.0},
                        {"epoch": 2.0, "train_loss": 0.5, "validation_mse": 0.5}],
            "best_epoch": 2, "best_validation_mse": 0.5, "stopped_early": False, "epochs_run": 2,
            "before": before, "after": after, "names": names,
            "clock": list(J15.CLOCK_COLUMNS),
            "controller": list(J15.J8.controller_indices(names)),
            "scales_verified": {"double": "test"}, "preconditions": {"double": "test"},
            "torch_backend_observed": {"double": "test", "torch_version": "TEST-DOUBLE"},
            "modules": J15.verify_modules(),
            "seed_order": ["test double"],
            "numpy_legacy_seed": {"call": "np.random.seed", "value": 123, "count": 1,
                                  "is_a_generator": False, "position": "test double"}}


def _body(tmproot: Path) -> int:
    src = (HERE / "v26c_j15_fresh_refit.py").read_text()
    tree = ast.parse(src)
    nodes = list(ast.walk(tree))
    ids = {t.string for t in tokenize.generate_tokens(io.StringIO(src).readline)
           if t.type == tokenize.NAME}
    prereg = json.loads(J15.PREREG.read_text())
    before_all = snapshot(HERE)
    leaf_exists_at_start = J15.authorized_leaf().exists()

    # ---------------------------------------------------------------- the guard itself ---------
    probes = (
        ("Path.write_bytes on the frozen preregistration",
         lambda: J15.PREREG.write_bytes(b"x")),
        ("Path.write_text of a marker in the real J14 leaf",
         lambda: (J15.J14_LEAF / J15.TECHNICAL_INVALID_NAME).write_text("x", encoding="utf-8")),
        ("Path.write_text of a lock beside the future J15 leaf",
         lambda: (J15.authorized_leaf().parent / ".lock_probe").write_text("x", encoding="utf-8")),
        ("Path.unlink of a real pinned source",
         lambda: (HERE / "v26c_j15_fresh_refit.py").unlink()),
        ("open(..., 'w') under the validation root",
         lambda: open(HERE / "_probe.txt", "w").close()),
        ("Path.open(..., 'w') on the frozen preregistration",
         lambda: J15.PREREG.open("w").close()),
        ("io.open(..., 'w') under the validation root",
         lambda: io.open(str(HERE / "_probe_io.txt"), "w").close()),
        ("os.rename under the validation root",
         lambda: os.rename(HERE / "_a", HERE / "_b")),
        ("shutil.rmtree of a real leaf", lambda: shutil.rmtree(J15.J14_LEAF)),
        ("Path.mkdir of the future j15_runs", lambda: (HERE / "j15_runs").mkdir()),
        ("np.savez_compressed under the validation root",
         lambda: np.savez_compressed(HERE / "_probe.npz", a=np.zeros(1))),
        ("os.open for writing under the validation root",
         lambda: os.open(str(HERE / "_probe_fd"), os.O_CREAT | os.O_WRONLY)),
    )
    for label, fn in probes:
        n = len(ATTEMPTS)
        expect(fn, AssertionError, f"the guard blocks {label}")
        check(len(ATTEMPTS) == n + 1, f"and records the attempt ({ATTEMPTS[-1]})")
    check(len(ATTEMPTS) == len(probes),
          f"MEASURED: {len(probes)} blocked attempts, all deliberate probes")
    check(not any((HERE / n).exists() for n in ("_probe.txt", "_probe_io.txt", "_probe.npz",
                                               "_probe_fd", "j15_runs")),
          "MEASURED: not one probe left a trace on disk")
    check(J15._sha_file(J15.PREREG) == J15.PIN_PREREG,
          "and the preregistration the probes aimed at is still byte-identical")
    check(sys.dont_write_bytecode is True,
          "MEASURED: the suite disables bytecode writing itself, before importing the runner")
    check(builtins.open.__name__ == "guarded_open" and io.open.__name__ == "guarded_open"
          and Path.open.__name__ == "guarded_path_open",
          "MEASURED: builtins.open, io.open AND Path.open are all guarded")
    (tmproot / "_writable.txt").write_text("ok", encoding="utf-8")
    check((tmproot / "_writable.txt").read_text() == "ok", "while the temp root stays writable")

    # ---------------------------------------------------------------- preregistration ----------
    check(prereg["kind"] == "ADDITIVE, IMMUTABLE, PREREGISTRATION"
          and prereg["stage_proposed"] == J15.STAGE
          == "V26C_J15_FRESH_35D_POST_MISMATCH_REFIT",
          "the prereg is additive, immutable and proposes the J15 stage")
    check("stage_authorised" not in prereg
          and prereg["authorisation_status"].startswith("NOT_GRANTED")
          and prereg["execution_permitted_now"] is False,
          "it grants no authorisation and does not permit its own execution")
    check(J15._sha_file(J15.PREREG) == J15.PIN_PREREG, "and is pinned by exact hash")
    expect(_tamper_prereg, J15Error_t(), "a tampered preregistration is refused")
    check(J15._sha_file(J15.PREREG) == J15.PIN_PREREG,
          "and the REAL preregistration is untouched afterwards")

    # ---------------------------------------------------------------- hyperparameters ----------
    hp = J15.verify_hyperparameters_are_j11s()
    check(hp["equal_to_j11"] and hp["equal_to_frozen_j8_source"], "the hyperparameters ARE J11's")
    check(hp["same_python_object_as_j11"] is False,
          "and the record says plainly that they are copies, not the same object - because J11 "
          "itself takes a copy")
    check(dict(J15.JULY_HP) == dict(J15.J11.JULY_HP) == dict(J15.J8.JULY_HP),
          "MEASURED: all three dicts are equal")
    check(dict(J15.JULY_HP) == {"seed": 123, "epochs": 400, "batch_size": 128,
                                "learning_rate": 5e-05, "validation_fraction": 0.2,
                                "patience": 60, "clip_weight": 1.0, "logstd_weight": 0.0,
                                "anchor_weight": 0.01, "trainable_first_layer_features": None},
          "and they are exactly the ten July values")
    check(J15.BEST_EPSILON == 1e-9 == J15.J11.BEST_EPSILON,
          "BEST_EPSILON is 1e-9, the same as J11's, and is preregistered here")
    check(prereg["hyperparameters"]["best_epsilon"] == 1e-9,
          "which J11 recorded in no prereg or receipt field")
    pg = prereg["gate"]
    check(pg["binding_count"] == 17 and pg["j11_binding_subset_count"] == 16
          and pg["j15_additional_binding_count"] == 1,
          "the preregistration commits to 16 + 1 = 17 binding checks BEFORE the fit runs")
    check("binding_identical_to_j11" not in pg,
          "and the ambiguous field is GONE - its name said 'identical' while it held 17 names")
    check(pg["identical_to_j11"] is False,
          "the prereg states plainly that this gate is NOT identical to J11's")
    check(tuple(pg["j11_binding_subset"]) == _J11_BINDING
          and tuple(pg["j15_additional_binding"]) == _J15_EXTRA,
          "j11_binding_subset holds J11's exact 16; j15_additional_binding holds only the 17th")
    check(set(pg["j11_binding_subset"]).isdisjoint(pg["j15_additional_binding"]),
          "the two fields are disjoint - nothing is counted twice")
    check(prereg["gate"]["the_seventeenth_gate"]["introduces_no_new_number"] is True,
          "and records that the 17th introduces no new number")
    check("governance_rule_recorded" in prereg
          and "EVERY phase closes with a dedicated user report" in
          prereg["governance_rule_recorded"]["rule"],
          "the binding governance rule - a user report closes every phase - is recorded")
    lits = {n.value for n in nodes if isinstance(n, ast.Constant)
            and isinstance(n.value, (int, float)) and not isinstance(n.value, bool)}
    for forbidden in (5e-05, 0.01, 60, 400, 128):
        check(forbidden not in lits or forbidden in (60, 400, 128),
              f"no hyperparameter is retyped as a literal in this runner ({forbidden})")
    check(5e-05 not in lits and 0.2 not in lits,
          "STATIC: the learning rate and the validation fraction appear as NO literal here")

    # ---------------------------------------------------------------- run_fit is J11's ---------
    j11_src = inspect.getsource(J15.J11.run_fit)
    j15_src = inspect.getsource(J15.run_fit)
    diff = "".join(difflib.unified_diff(j11_src.splitlines(True), j15_src.splitlines(True),
                                        fromfile="J11.run_fit", tofile="J15.run_fit", n=1))
    check(diff == J15.RUN_FIT_EXPECTED_DIFF,
          "MEASURED: run_fit differs from J11's by EXACTLY the declared diff, and nothing else")
    changed = [l for l in diff.splitlines() if l[:1] in "+-" and l[:3] not in ("+++", "---")]
    check(len(changed) == 18, f"MEASURED: {len(changed)} changed lines, all declared")
    check(not any("JULY_HP" in l or "Adam(" in l or "mse_loss" in l or "patience" in l
                  or "permutation" in l or "backward" in l or "step()" in l
                  for l in changed if l.startswith(("+", "-")) and "adam_resolved" not in l),
          "and NONE of them touches the optimizer, the loss, the shuffle or the stopping rule")
    check(any("torch_version" in l for l in changed)
          and any("adam_resolved_arguments" in l for l in changed),
          "the two additions are the pure-read diagnostics J11 left unrecorded")

    # ---------------------------------------------------------------- the aggregate ------------
    data = J15.build_aggregate()
    obs, act = data["observations"], data["actions"]
    check(obs.shape == (25567, 35) and act.shape == (25567, 2),
          f"MEASURED: the aggregate is {obs.shape}/{act.shape}")
    check(obs.dtype == np.float32 and act.dtype == np.float32, "float32 throughout")
    check(J15.TOTAL_ROWS == 16713 + 8 * 500 + 8 * 500 + 854 == 25567,
          "MEASURED: 16713 + 8x500 + 8x500 + 854 = 25567")
    ids_ = [b["id"] for b in data["blocks"]]
    check(ids_ == ["j7_nominal", "j7_recovery", "cell_B", "cell_C", "j14_increment"],
          f"five blocks, in order: {ids_}")
    check([b["rows"] for b in data["blocks"]] == [16000, 713, 4000, 4000, 854],
          "with the declared row counts")
    check([b["repeat"] for b in data["blocks"]] == [32, 1, 8, 8, 1],
          "and the declared repeat factors - 1 on the new rows")
    check(float(np.max(np.abs(obs[:, 0]))) == 0.0 and float(np.max(np.abs(obs[:, 1]))) == 0.0,
          "MEASURED: clock columns 0 and 1 are EXACTLY zero over all 25567 rows")

    # the trap: the J10R1 cells are NOT clock-zeroed on disk
    raw_b = np.load(J15.CELL_DATASETS["B"][0], allow_pickle=False)["observations"]
    check(float(np.max(np.abs(raw_b[:, 1]))) == 1.0,
          "MEASURED: cell B on disk has gait_phase_cos = 1.0, NOT zero - the projection is this "
          "stage's job and skipping it would poison 8000 rows")
    check(float(np.max(np.abs(obs[16713:17213, 1]))) == 0.0,
          "and the same rows inside the aggregate are exactly zero")

    # tile, not repeat
    head = obs[16713:17213]
    check(np.array_equal(obs[17213:17713], head),
          "MEASURED: cell B is TILED - the second copy equals the first block, not row-repeated")
    check(not np.array_equal(obs[16713:16715], np.repeat(head[:1], 2, axis=0)),
          "and np.repeat semantics are measurably absent")

    # the J11 prefix survives untouched
    j11_agg = np.load(J15.J11_LEAF / "v26c_j11_aggregate_dataset.npz", allow_pickle=False)
    check(np.array_equal(obs[:24713], j11_agg["observations"])
          and np.array_equal(act[:24713], j11_agg["actions"]),
          "MEASURED: rows [0:24713] are BIT-IDENTICAL to the J11 aggregate - the 854 rows are "
          "appended, so J11's indices are unchanged and the two fits are comparable")
    check(np.array_equal(obs[24713:], np.load(J15.J14_DATASET,
                                              allow_pickle=False)["observations"]),
          "and rows [24713:25567] are bit-identical to the J14 increment")

    # ---------------------------------------------------------------- the increment ------------
    new = J15.load_j14()
    check(new["rows"] == 854 and new["per_cell"] == {"E": 500, "F": 354},
          f"MEASURED: 854 rows, {new['per_cell']}")
    check(new["post_mismatch_rows"] == 671 and new["pre_mismatch_rows"] == 183,
          "MEASURED: 671 post-mismatch, 183 pre-mismatch - the 671 are the region J13 identified")
    check(new["seeds"] == [124, 125], f"MEASURED: seeds {new['seeds']}")
    check(new["sealed_seeds_present"] == [], "and NO sealed seed is present")
    check(new["not_truncated"] and new["repeat"] == 1,
          "not truncated, not filtered, repeat 1")
    check(J15.NEW_CELL_SPANS == (("E", 0, 500), ("F", 500, 854)),
          "MEASURED: E and F are contiguous blocks in that order - load_j14 refuses otherwise, "
          "because the binding gate's slices depend on it")
    check(sorted(new["provenance_columns"]) == ["cell", "post_mismatch", "seed", "step",
                                                "time_before"],
          "every row carries its provenance")

    # ---------------------------------------------------------------- the split ----------------
    split = J15.build_split(J15.TOTAL_ROWS)
    check((split["n_val"], split["n_train"]) == (5113, 20454),
          f"MEASURED: split {split['n_val']}/{split['n_train']}")
    check(split["n_val"] + split["n_train"] == 25567, "which covers every row exactly once")
    check(split["n_val"] == max(1, int(round(25567 * 0.2))),
          "and reproduces max(1, int(round(rows * 0.2)))")
    check(split["validation_sorted"] and split["train_order_preserved"]
          and not split["train_is_sorted"],
          "validation sorted, training ORDER PRESERVED - sorting it would change every epoch")
    check(len(set(split["val_idx"].tolist()) & set(split["train_idx"].tolist())) == 0,
          "the two halves are disjoint")
    check(J15.EXPECTED_N_VAL == 5113 and J15.EXPECTED_N_TRAIN == 20454,
          "and the declared numbers are VERIFIED, never assumed")

    # ---------------------------------------------------------------- the parent ---------------
    parent = J15.load_parent_state()
    check(J15._sha_file(J15.PARENT_MODULE_DIR / "module_state.pkl") == J15.PIN_PARENT_STATE
          == "0f182ea9f8939e2b7824e85c12c57343309c444680682b9bce5858dd74f9d130",
          "the parent is the J2 module state, by exact hash")
    check("j2_runs" in str(J15.PARENT_MODULE_DIR) and "j11_runs" not in str(
        J15.PARENT_MODULE_DIR), "and it lives under j2_runs, NOT j11_runs")
    check(not any("critic" in k or k.startswith("vf") for k in parent),
          "the parent carries no critic tensor")
    check(sorted(parent) == sorted(J15.STATE_KEYS) and len(parent) == 10,
          "ten actor keys, exactly the declared set")
    check(J15.PIN_J11_STATE != J15.PIN_PARENT_STATE,
          "the J11 state is a DIFFERENT artefact and is pinned only as negative evidence")
    j11_state_read = [n for n in nodes if isinstance(n, ast.Call)
                      and isinstance(n.func, ast.Attribute) and n.func.attr == "load"
                      and any(isinstance(d, ast.Name) and d.id == "J11_STATE"
                              for d in ast.walk(n))]
    check(not j11_state_read, "STATIC: nothing in this runner loads the J11 state as weights")

    # ---------------------------------------------------------------- the gate -----------------
    gm = J15.gate_matrix()
    check(gm["binding_count"] == 17 and len(J15.J15_BINDING_NAMES) == 17,
          f"MEASURED: {gm['binding_count']} binding checks - J11's 16 plus the 17th")
    check(sorted(J15.J15_BINDING_NAMES) == sorted(_J11_BINDING + _J15_EXTRA),
          "exactly J11's names one for one, plus j14_increment_rmse_decreases")
    check(J15.J11_BINDING_SUBSET == _J11_BINDING and J15.J15_ADDITIONAL_BINDING == _J15_EXTRA,
          "the runner keeps the two sets as SEPARATE named tuples, so the subset relation is a "
          "checkable fact and not a sentence")
    check(J15.J15_BINDING_NAMES == J15.J11_BINDING_SUBSET + J15.J15_ADDITIONAL_BINDING,
          "and the binding set is literally their concatenation: 16 + 1 = 17")
    check(set(_J11_BINDING) < set(J15.J15_BINDING_NAMES),
          "J11's binding set is a strict SUBSET - nothing of J11's was dropped or renamed")
    check(gm["identical_to_j11"] is False
          and gm["relation_to_j11"].startswith(
              "the 16-name J11 binding subset is preserved, name for name, and J15 adds one "
              "binding rule"),
          "and the record states the preservation of the 16-name SUBSET plus one added rule, "
          "never that the J15 gate is J11's unchanged")
    check("16 + 1 = 17" in gm["relation_to_j11"], "with the arithmetic spelled out")
    check("FIVE binding RMSE rules" in gm["no_invented_thresholds"],
          "the gate matrix too speaks of FIVE binding RMSE rules, not four")
    check(all("J11, unchanged" not in b.get("source", "") for b in gm["binding"]),
          "no binding rule still calls itself 'J11, unchanged'")
    check(all(b.get("margin", "none") == "none" for b in gm["binding"] if "margin" in b),
          "no margin is invented on any binding rule")
    seventeenth = next(b for b in gm["binding"]
                       if b["name"] == "j14_increment_rmse_decreases")
    check(seventeenth["not_a_new_threshold"].startswith("it is the same strict inequality"),
          "the 17th introduces NO new number: same strict inequality, measured baseline")
    check("J13" in seventeenth["source"] and "blocco E" in seventeenth["source"],
          "and it cites the approved J13 report that preregistered it")
    lits17 = {n.value for n in ast.walk(ast.parse(inspect.getsource(J15.gate_matrix)))
              if isinstance(n, ast.Constant) and isinstance(n.value, float)}
    check(not lits17, f"STATIC: the gate matrix contains NO float literal at all ({lits17})")
    for name in ("j14_cell_E_rmse", "j14_cell_F_rmse", "j14_post_mismatch_rmse",
                 "j14_pre_mismatch_rmse", "j14_phase_invalid_fraction", "j11_prefix_rmse"):
        check(name in gm["diagnostics_not_binding"], f"{name} stays DIAGNOSTIC")
    check("j14_increment_rmse" not in gm["diagnostics_not_binding"],
          "and the whole-block RMSE is no longer listed as a diagnostic - it is a gate now")
    w = gm["what_stays_diagnostic_and_why"]
    check("new rule" in w["cells_E_and_F_separately"],
          "E and F stay separate for VISIBILITY; a per-cell gate would be a new rule")
    check("never used to filter" in w["post_mismatch_671_and_pre_mismatch_183"],
          "the 671/183 split is reported, never used to filter or weight")
    check("no preregistered direction" in w["comparisons_with_j11"],
          "and the J11 comparison cannot be a gate")
    check("NOTHING about closed-loop" in gm["supervised_only"],
          "the gate says plainly that it is supervised only")

    # ---------------------------------------------------------------- inertia ------------------
    check("torch" not in sys.modules, "MEASURED: torch is NOT imported by this suite")
    check("ray" not in sys.modules, "and neither is ray")
    pf = J15.preflight()
    check(pf["verdict"] == "GO" and not pf["blockers"] if not leaf_exists_at_start else True,
          f"the preflight is GO with no blockers ({pf['blockers']})")
    check(pf["inert"]["torch_imported_by_this_preflight"] is False,
          "and it imported no torch")
    check(pf["inert"]["sealed_seeds_read"] == 0 and pf["seeds"]["sealed_never_read"]
          == [126, 127, 128], "seeds 126, 127, 128 remain sealed and unread")
    check(pf["sources"]["count"] == 23, f"MEASURED: {pf['sources']['count']} pinned sources")
    check(pf["parent"]["is_j2"] and not pf["parent"]["is_j11"] and not pf["parent"]["is_july"],
          "the parent is J2 - not J11, not July")
    check(pf["parent"]["leaf_has_commit_verification"] is False,
          "and the preflight states plainly that the J2 leaf carries no commit_verification: it "
          "predates the convention, so integrity rests on the file hashes")
    check(not J15.PREFLIGHT_SENTINEL.exists(), "the preflight created no sentinel")
    check("torch" not in sys.modules, "and STILL no torch after the preflight")

    # ---------------------------------------------------------------- refusals -----------------
    expect(lambda: J15.validate_stage(None), J15Error_t(), "a missing stage token is refused")
    expect(lambda: J15.validate_stage("V26C_J14_POST_MISMATCH_DAGGER_DATASET"), J15Error_t(),
           "another stage's token is refused")
    expect(lambda: J15.validate_out(None), J15Error_t(), "--fit without --out is refused")
    expect(lambda: J15.validate_out("relative/path"), J15Error_t(), "a relative --out is refused")
    expect(lambda: J15.validate_out(str(tmproot / "somewhere_else")), J15Error_t(),
           "an --out that is not the authorised leaf is refused")
    expect(lambda: J15.commit(str(J15.authorized_leaf()), J15.STAGE, fit=fake_fit()),
           J15Error_t(), "an INJECTED fit may never write to the authoritative root")

    # ---------------------------------------------------------------- materialisation ----------
    # NON-AUTHORITATIVE, in a temp root, with an injected double. The real fit path is never run.
    out_root = tmproot / "authoritative_double"
    J15.OUTPUT_ROOT_OVERRIDE = out_root
    try:
        expect(lambda: J15.commit(str(J15.authorized_leaf()), J15.STAGE), J15Error_t(),
               "a REAL fit refuses to run into a redirected root")
        fit = fake_fit()
        gate = J15.audit(fit)
        check(gate["pass"] is True and gate["failed"] == [],
              f"the double passes all 17 binding checks ({gate['failed']})")
        check(sorted(gate["binding"]) == sorted(_J11_BINDING + _J15_EXTRA),
              "and the binding set is J11's 16 plus the 17th")
        rel = gate["relation_to_j11"]
        check(gate["identical_to_j11"] is False and "binding_identical_to_j11" not in gate,
              "audit() reports identical_to_j11 FALSE and carries no stale boolean")
        check(tuple(rel["j11_binding_subset"]) == _J11_BINDING
              and rel["j11_binding_subset_count"] == 16
              and tuple(rel["j15_additional_binding"]) == _J15_EXTRA
              and rel["j15_additional_binding_count"] == 1
              and rel["binding_count"] == 17,
              "and names the exact J11 subset and the single extra, 16 + 1 = 17")
        check(rel["j11_set_preserved_exactly"] is True
              and rel["names_j15_dropped_or_renamed_from_j11"] == [],
              "MEASURED: not one J11 binding name was dropped or renamed")
        nit = gate["no_invented_thresholds"]
        check("FIVE RMSE subsets" in nit and "854-row J14 block" in nit,
              "no_invented_thresholds says FIVE binding RMSE subsets, including the J14 block")
        check("Only the J14 block AS A WHOLE binds" in nit
              and "remain DIAGNOSTIC and bind nothing" in nit,
              "and states that only the whole block binds - E/F, post/pre-mismatch, "
              "phase-invalid and the J11 comparisons stay diagnostic")
        check("The J14 subsets are DIAGNOSTIC and bind nothing" not in nit,
              "the stale sentence is gone")
        check(gate["rmse"]["j14_increment"]["binding"] is True
              and gate["rmse"]["j14_increment"]["rows"] == 854
              and gate["rmse"]["j14_increment"]["slice"] == [24713, 25567],
              "the 17th binds the WHOLE 854-row block, rows [24713:25567]")
        d = gate["diagnostics"]
        check(d["j14_cell_E_rmse"]["rows"] == 500 and d["j14_cell_E_rmse"]["slice"] == [24713, 25213]
              and d["j14_cell_F_rmse"]["rows"] == 354
              and d["j14_cell_F_rmse"]["slice"] == [25213, 25567],
              "E and F are reported separately: 500 at [24713:25213], 354 at [25213:25567]")
        check(d["j14_post_mismatch_rmse"]["rows"] == 671
              and d["j14_pre_mismatch_rmse"]["rows"] == 183,
              "post-mismatch 671 and pre-mismatch 183, both diagnostic")
        check(d["j14_phase_invalid_fraction"]["rows_flagged"] == 671
              and d["j14_phase_invalid_fraction"]["rows_total"] == 854
              and d["j14_phase_invalid_fraction"]["binding"] is False,
              "the phase-invalid fraction is 671/854 and stays diagnostic")
        check(all(not d[k]["binding"] for k in ("j14_cell_E_rmse", "j14_cell_F_rmse",
                                                "j14_post_mismatch_rmse", "j14_pre_mismatch_rmse",
                                                "j14_phase_invalid_fraction", "j11_prefix_rmse")),
              "and NONE of the six diagnostics binds anything")
        res = J15.commit(str(J15.authorized_leaf()), J15.STAGE, fit=fit, gate=gate)
        leaf = Path(res["leaf"])
        check(res["authoritative"] is False,
              "MEASURED: the leaf declares itself NON-AUTHORITATIVE - it is a test double")
        check(json.loads((leaf / "v26c_j15_fresh_refit_receipt.json").read_text())
              ["injected_fit_double"] is True, "and the receipt says so too")
        files = sorted(q.relative_to(leaf).as_posix() for q in leaf.rglob("*") if q.is_file())
        check(files == ["commit_verification.json", "history.json",
                        "rl_module/actor_feature_manifest.json",
                        "rl_module/class_and_ctor_args.pkl", "rl_module/metadata.json",
                        "rl_module/module_state.pkl", "v26c_j15_aggregate_dataset.npz",
                        "v26c_j15_fresh_refit_receipt.json"],
              f"exactly the eight declared files: {files}")
        cv = json.loads((leaf / "commit_verification.json").read_text())
        check(cv["pass"] is True and not cv["paths_missing"] and not cv["hash_mismatches"],
              f"post-commit verification PASSES, {cv['files_checked']} files re-hashed")
        check(not (leaf / "TECHNICAL_INVALID").exists(),
              "and the born-invalid marker was removed as the LAST write")
        man = json.loads((leaf / "rl_module" / "actor_feature_manifest.json").read_text())
        check(man["is_a_copy_of_the_parent_manifest"] is False
              and man["module_state_sha256"] == res["module_state_sha256"],
              "the manifest is REGENERATED and names the module beside it")
        check(man["lineage"]["not_derived_from"]["j11"].startswith("J11 is the actor that FAILED"),
              "and states plainly that J11 is not its parent")
        check(man["critic_contract"]["present"] is False
              and "RANDOMLY INITIALISED" in man["critic_contract"]["meaning"],
              "the critic is declared ABSENT, not preserved - a consumer gets a random critic")
        check(man["deployable"] is False and "PENDING" in man["closed_loop_qualification"],
              "nothing is promoted and closed-loop qualification is PENDING")
        for name in ("class_and_ctor_args.pkl", "metadata.json"):
            check(J15._sha_file(leaf / "rl_module" / name) == J15.SIDECARS[name],
                  f"the sidecar {name} is byte-identical to the parent's")
        rec = json.loads((leaf / "v26c_j15_fresh_refit_receipt.json").read_text())
        rg = rec["gate"]
        check(rg["schema"] == "v26c_j15_gate.2" and rg["identical_to_j11"] is False
              and "binding_identical_to_j11" not in rg,
              "the RECEIPT carries the truthful relation, not the stale boolean")
        check(rg["relation_to_j11"]["binding_count"] == 17
              and rg["relation_to_j11"]["j11_binding_subset_count"] == 16,
              "and records 16 preserved + 1 added = 17")
        check("binding_identical_to_j11" not in json.dumps(rec),
              "MEASURED: the string binding_identical_to_j11 appears NOWHERE in the receipt")
        check("four subsets" not in json.dumps(rec),
              "and neither does the stale phrase 'four subsets'")
        check(rec["actor_digest"] and rec["source_actor_digest"],
              "the receipt records actor_digest AND source_actor_digest - J11 recorded neither")
        check(rec["lineage"]["not_j11"]["j11_was_loaded"] is False,
              "and records that J11 was never loaded")
        check(J15.STAGING_NAME not in json.dumps(rec) and str(out_root) not in json.dumps(rec),
              "no staging path and no override root leak into the receipt")
        expect(lambda: J15.commit(str(J15.authorized_leaf()), J15.STAGE, fit=fake_fit()),
               J15Error_t(), "a SECOND materialisation is refused - no-clobber")
        check(not any(q.name.startswith((".lock_", ".staging_"))
                      for q in leaf.parent.iterdir()),
              "and no lock or staging directory is left behind")
    finally:
        J15.OUTPUT_ROOT_OVERRIDE = None

    # ---------------------------------------------------------------- tamper -------------------
    try:
        with use_mirror(MIRROR):
            # inside this context the module constants ALREADY point at the mirror
            bad = J15.J14_DATASET
            check(str(MIRROR) in str(bad), "the tamper target is inside the temp mirror")
            bad.write_bytes(bad.read_bytes() + b"\x00")
            expect(J15.load_j14, J15Error_t(), "a tampered J14 increment is refused by hash")
            expect(J15.verify_sources, J15Error_t(), "and by verify_sources, naming the file")
    finally:
        reset_mirror(MIRROR)      # OUTSIDE the context, with the real constants restored
    check(J15._sha_file(J15.J14_DATASET) == J15.PIN_J14_DATASET,
          "MEASURED: the REAL J14 increment was never touched")

    try:
        with use_mirror(MIRROR):
            marker = J15.J14_LEAF / "TECHNICAL_INVALID"
            check(str(MIRROR) in str(marker), "the marker target is inside the temp mirror")
            marker.parent.mkdir(parents=True, exist_ok=True)
            marker.write_text("x", encoding="utf-8")
            expect(lambda: J15.verify_source_leaf(J15.J14_LEAF, label="J14",
                                                  expect_verdict=None),
                   J15Error_t(), "a source leaf carrying TECHNICAL_INVALID is refused")
    finally:
        reset_mirror(MIRROR)
    check(not (J15.J14_LEAF / "TECHNICAL_INVALID").exists(),
          "MEASURED: the REAL J14 leaf carries no marker")

    # ---------------------------------------------------------------- static ------------------
    for name in ("PPOConfig", "train_ppo", "adapt_actor", "forward_exploration", "PPO"):
        check(name not in ids, f"the runner never references {name}")
    check("import ray" not in src and "from ray" not in src, "and never imports ray")
    # the runner may NAME the retired field inside a refusal; it may never EMIT it. So the check
    # is on dict KEYS, by AST, not on raw text - a substring test would flag the guard itself.
    dict_keys = {k.value for n in nodes if isinstance(n, ast.Dict) for k in n.keys
                 if isinstance(k, ast.Constant) and isinstance(k.value, str)}
    check("binding_identical_to_j11" not in dict_keys,
          "STATIC: the runner never EMITS binding_identical_to_j11 as a field")
    check("identical_to_j11" in dict_keys and "relation_to_j11" in dict_keys,
          "and emits identical_to_j11 plus relation_to_j11 instead")
    guard = [n for n in nodes if isinstance(n, ast.Compare)
             and isinstance(n.left, ast.Constant)
             and n.left.value == "binding_identical_to_j11"]
    check(len(guard) == 1,
          "the ONLY mention of the retired field is the guard that refuses a prereg carrying it")
    for stale in ("four binding subsets", "on four subsets", "J11's binding gate, unchanged",
                  "The J14 subsets are DIAGNOSTIC and bind nothing",
                  # the exact docstring the architect's rev2 audit found. My previous check
                  # listed four phrases I had chosen myself and I then claimed "no stale string"
                  # - a claim wider than what was tested. The structural rule below replaces
                  # that habit; this literal stays as a regression anchor.
                  "Binding rules are J11's, unchanged"):
        check(stale not in src, f"STATIC: no stale prose in the runner ({stale!r})")

    # STRUCTURAL RULE, not a phrase list I picked: no string ANYWHERE in the runner or the
    # preregistration may ASSERT that the J15 gate, or its binding rules as a set, are J11's
    # unchanged. Negations are allowed - "this gate is NOT ... unchanged" is a correct sentence -
    # so the patterns match the CLAIM, not the word.
    CLAIMS = (
        r"(?<!not )(?:binding\s+)?(?:rules?|gate)\s+(?:are|is)\s+J11'?s?,?\s*unchanged",
        r"J11'?s\s+(?:binding\s+)?gate,?\s*unchanged",
        r"unchanged\s+and\s+name\s+for\s+name",
        r"J11'?s\s+\d+\s+binding\s+checks,\s*unchanged",
    )
    def offending(text: str) -> list[str]:
        return [m.group(0) for pat in CLAIMS
                for m in re.finditer(pat, text, re.IGNORECASE)]

    runner_strings = [(n.lineno, n.value) for n in nodes
                      if isinstance(n, ast.Constant) and isinstance(n.value, str)]
    hits = [(ln, o) for ln, v in runner_strings for o in offending(v)]
    check(not hits, f"STRUCTURAL: no string in the runner CLAIMS the J15 gate is J11's "
                    f"unchanged ({hits[:3]})")
    check(offending("Binding rules are J11's, unchanged.") and
          offending("J11's binding gate, unchanged and name for name, PLUS one"),
          "and the rule PROVES it bites on both strings the audits actually found")
    check(not offending("This gate is NOT identical to J11's and is not described as unchanged"),
          "while a NEGATION is correctly left alone - the rule targets the claim, not the word")

    prereg_text = J15.PREREG.read_text()
    check(not offending(prereg_text),
          f"STRUCTURAL: the preregistration makes no such claim either "
          f"({offending(prereg_text)[:3]})")
    check("unchanged and name for name" not in prereg_text,
          "and the ambiguous 'unchanged and name for name' is gone from the prereg")
    check(prereg["gate"]["principle"].startswith(
        "the 16-name J11 binding subset is preserved, name for name, and J15 adds one binding "
        "rule"), "the prereg principle states the preservation of the SUBSET and the one addition")
    check("wording_rule" in prereg["gate"],
          "and records the wording rule it holds itself to")
    gm_doc = inspect.getdoc(J15.gate_matrix) or ""
    check(not offending(gm_doc) and "16-name J11 binding subset is PRESERVED" in gm_doc,
          "gate_matrix's own docstring states the subset preservation, not an unchanged gate")
    for fn in (J15.audit, J15.build_receipt, J15.gate_matrix, J15.verify_prereg):
        check(not offending(inspect.getdoc(fn) or ""),
              f"and neither does {fn.__name__}'s docstring")
    check(all("unchanged" not in b.get("source", "") for b in gm["binding"]),
          "no binding rule labels its source with 'unchanged'")
    torch_imports = [n.lineno for n in nodes
                     if isinstance(n, ast.Import) and any(a.name == "torch" for a in n.names)]
    check(len(torch_imports) == 1, "torch is imported EXACTLY once")
    fn = next(f for f in nodes if isinstance(f, ast.FunctionDef) and f.name == "run_fit")
    check(fn.lineno < torch_imports[0] < fn.end_lineno,
          f"and only INSIDE run_fit (line {torch_imports[0]}), never at module level")
    rm = [n for n in nodes if isinstance(n, ast.Call)
          and isinstance(n.func, ast.Attribute) and n.func.attr == "rmtree"]
    check(len(rm) == 1 and isinstance(rm[0].args[0], ast.Name)
          and rm[0].args[0].id == "staging_created",
          "exactly ONE recursive removal, and its only argument is staging_created")
    check("O_CREAT | os.O_EXCL" in src, "the lock uses O_CREAT|O_EXCL")
    marker_writes = [n.lineno for n in nodes if isinstance(n, ast.Call)
                     and isinstance(n.func, ast.Attribute) and n.func.attr == "write_text"
                     and any(isinstance(d, ast.Name) and d.id == "TECHNICAL_INVALID_NAME"
                             for d in ast.walk(n.func.value))]
    rename_line = next(n.lineno for n in nodes if isinstance(n, ast.Call)
                       and isinstance(n.func, ast.Attribute) and n.func.attr == "rename"
                       and isinstance(n.func.value, ast.Name) and n.func.value.id == "os")
    check(marker_writes and min(marker_writes) < rename_line,
          f"STATIC: the marker is written into STAGING at line {min(marker_writes)}, BEFORE the "
          f"rename at line {rename_line}")
    unlinks = [n.lineno for n in nodes if isinstance(n, ast.Call)
               and isinstance(n.func, ast.Attribute) and n.func.attr == "unlink"
               and isinstance(n.func.value, ast.Name) and n.func.value.id == "marker"]
    check(unlinks and min(unlinks) > rename_line, "and removed only AFTER the commit")

    # ---------------------------------------------------------------- hermeticity --------------
    snap_fn = next(n for n in ast.walk(ast.parse(TEST_SRC))
                   if isinstance(n, ast.FunctionDef) and n.name == "snapshot")
    body = list(snap_fn.body)
    if (isinstance(body[0], ast.Expr) and isinstance(body[0].value, ast.Constant)
            and isinstance(body[0].value.value, str)):
        body.pop(0)
    consts = {n.value for b in body for n in ast.walk(b)
              if isinstance(n, ast.Constant) and isinstance(n.value, str)}
    check("__pycache__" not in consts,
          "STATIC: snapshot()'s CODE applies no exclusion - __pycache__ is inside the guarded set")
    fd_rel = [n.lineno for n in ast.walk(ast.parse(TEST_SRC)) if isinstance(n, ast.Call)
              for kw in n.keywords if kw.arg == "dir_fd"]
    check(not fd_rel,
          "STATIC: this suite makes NO direct fd-relative call, so the dir_fd delegation is "
          "reachable only from shutil.rmtree's own descent - a SCOPED statement, not a universal "
          "fd-relative guarantee")
    check(not (HERE / "j15_runs").exists() if not leaf_exists_at_start else True,
          "MEASURED: this suite never created the authorised j15_runs")
    check(snapshot(HERE) == before_all,
          "MEASURED: not one byte under the validation root changed across the WHOLE suite")

    print(json.dumps({"selftest": "PASS", "checks": CHECKS}, indent=1))
    return 0


def J15Error_t():
    return J15.J15Error


def _tamper_prereg():
    """Append a byte to the MIRRORED preregistration and prove the runner refuses it."""
    try:
        with use_mirror(MIRROR):
            p = J15.PREREG                      # already the mirrored path in this context
            assert str(MIRROR) in str(p), "refusing to tamper outside the mirror"
            p.write_bytes(p.read_bytes() + b" ")
            J15.verify_prereg()
    finally:
        reset_mirror(MIRROR)


_J11_BINDING = (
    "integrity_keys_and_shapes_match_parent", "integrity_all_parameters_finite",
    "integrity_clock_bit_zero", "integrity_aliases_bit_identical",
    "integrity_logstd_bit_identical_to_parent", "integrity_no_critic_key",
    "integrity_inputs_unchanged", "integrity_aggregate_reproduces_content_hashes",
    "integrity_split_counts_as_declared", "integrity_best_state_reconstructible_from_history",
    "integrity_all_metrics_finite", "aggregate_rmse_decreases", "recovery_rmse_decreases",
    "cell_B_unique_rmse_decreases", "cell_C_unique_rmse_decreases", "controller_columns_nonzero",
)

# the 17th, promoted by the architect on 2026-08-27 on the authority of the approved J13 report
_J15_EXTRA = ("j14_increment_rmse_decreases",)


if __name__ == "__main__":
    raise SystemExit(main())
